### ISSUE TITLE
screenshots

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/vector-addition-equations#2]
This is a new sim, so it needs a main and alternate screenshots.  It's a derivative of vector-additions (just the Equations screen).

**Comment by arouinfar** [comment]
@KatieWoe here are the desired screenshots. Please take these during rc testing.

Main
![Vector Addition_ Equations screenshot (3)](https://user-images.githubusercontent.com/8419308/67353922-02b24f00-f511-11e9-850c-65ed710b28c8.png)

Alt 1
![Vector Addition_ Equations screenshot (1)](https://user-images.githubusercontent.com/8419308/67353886-f0381580-f510-11e9-93d7-46cc4bbb8de1.png)

Alt 2
![Vector Addition_ Equations screenshot (5)](https://user-images.githubusercontent.com/8419308/67353940-0fcf3e00-f511-11e9-97ab-34b267c4360f.png)

Alt 3
![Vector Addition_ Equations screenshot](https://user-images.githubusercontent.com/8419308/67353881-ea423480-f510-11e9-978c-114d888dde9b.png)

**Comment by KatieWoe** [comment]
Let me know if these are good
![vector-addition-equations-screenshot](https://user-images.githubusercontent.com/41024075/67436235-27f39b80-f5ab-11e9-9279-27f10f9a8cb1.png)
![vector-addition-equations-screenshot-alt1](https://user-images.githubusercontent.com/41024075/67436236-27f39b80-f5ab-11e9-8f42-2dfe7cfea598.png)
![vector-addition-equations-screenshot-alt2](https://user-images.githubusercontent.com/41024075/67436238-27f39b80-f5ab-11e9-8df9-73fc9ad46edf.png)
![vector-addition-equations-screenshot-alt3](https://user-images.githubusercontent.com/41024075/67436239-288c3200-f5ab-11e9-806f-cf097694f1ae.png)

**Comment by pixelzoom** [comment]
@KatieWoe will you be checking these into GitHub, or would you like me to?

**Comment by KatieWoe** [comment]
Done in above commits
